### ISSUE TITLE
Auto close of panels when using checkbox field

### ISSUE THREAD

**Issue by llasic** [jforaker/react-accordion-with-header#3]
I have a list of checkbox inside the accordion but whenever i click the checkbox, all panels closes

**Comment by jforaker** [comment]
Could you provide some sample code so I can take a look? @llasic

**Comment by jforaker** [comment]
@llasic What kind of checkbox are you using? This is what I am seeing with a basic html input checkbox:

Also make sure you have the `multipleOkay={true}` prop on the top level `AccordionWithHeader` component.

![kapture 2018-03-16 at 19 33 44](https://user-images.githubusercontent.com/2042031/37548821-02a76370-2951-11e8-8e77-fea032cd8d7a.gif)
