### ISSUE TITLE
Cannot expand accordions added after componentdidmount

### ISSUE THREAD

**Issue by mklengs** [jforaker/react-accordion-with-header#9]
I'm trying to have a accordionWithHeader component that has a changing amount of nodes. The accordions exist in an array/list that can be added to and removed from. They render fine but they do not open/close without leaving the page and forcing the component to unmount and remount.

**Comment by jforaker** [comment]
Can you post a code snippet that demonstrates the behavior you are talking about? Here is a sandbox to get started: https://codesandbox.io/s/hopeful-lamport-0dzvo?file=/src/App.js

**Comment by jforaker** [comment]
EDIT:  Nice catch!  Indeed dynamically added `AccordionNode`'s don't behave properly: 
Demo of the behavior: https://codesandbox.io/s/romantic-pare-2hzsd?file=/src/App.js:637-650  you can see the newly added ones dont open when clicked 🐛

**Comment by jforaker** [comment]
fixed via pull #10 
current version is `react-accordion-with-header@0.1.3`
